<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="gestionUsuarios.aspx.vb" Inherits="lab2_.gestionUsuarios" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="../StyleSheet1.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    <div>
    
    </div>
        <asp:Panel ID="Panel1" runat="server" Font-Bold="True" Font-Size="XX-Large" ForeColor="#FF6600" HorizontalAlign="Center" style="z-index: -2; left: 11px; top: 47px; position: absolute; height: 72px; width: 1288px">
            Gestión De Usuarios<br />
            <br />
            <br />
            <br />
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="email" DataSourceID="SqlDataSource1" Font-Size="Medium" ForeColor="#333333" GridLines="None" Height="16px" Width="16px">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:BoundField DataField="email" HeaderText="email" ReadOnly="True" SortExpression="email" />
                    <asp:BoundField DataField="nombre" HeaderText="nombre" SortExpression="nombre" />
                    <asp:BoundField DataField="pregunta" HeaderText="pregunta" SortExpression="pregunta" />
                    <asp:BoundField DataField="respuesta" HeaderText="respuesta" SortExpression="respuesta" />
                    <asp:BoundField DataField="dni" HeaderText="dni" SortExpression="dni" />
                    <asp:CheckBoxField DataField="confirmado" HeaderText="confirmado" SortExpression="confirmado" />
                    <asp:BoundField DataField="grupo" HeaderText="grupo" SortExpression="grupo" />
                    <asp:BoundField DataField="tipo" HeaderText="tipo" SortExpression="tipo" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:HADS11_TareasConnectionString %>" DeleteCommand="DELETE FROM [Usuarios] WHERE [email] = @email" InsertCommand="INSERT INTO [Usuarios] ([email], [nombre], [pregunta], [respuesta], [dni], [confirmado], [grupo], [tipo]) VALUES (@email, @nombre, @pregunta, @respuesta, @dni, @confirmado, @grupo, @tipo)" SelectCommand="SELECT [email], [nombre], [pregunta], [respuesta], [dni], [confirmado], [grupo], [tipo] FROM [Usuarios]" UpdateCommand="UPDATE [Usuarios] SET [nombre] = @nombre, [pregunta] = @pregunta, [respuesta] = @respuesta, [dni] = @dni, [confirmado] = @confirmado, [grupo] = @grupo, [tipo] = @tipo WHERE [email] = @email">
                <DeleteParameters>
                    <asp:Parameter Name="email" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="email" Type="String" />
                    <asp:Parameter Name="nombre" Type="String" />
                    <asp:Parameter Name="pregunta" Type="String" />
                    <asp:Parameter Name="respuesta" Type="String" />
                    <asp:Parameter Name="dni" Type="Int32" />
                    <asp:Parameter Name="confirmado" Type="Boolean" />
                    <asp:Parameter Name="grupo" Type="String" />
                    <asp:Parameter Name="tipo" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="nombre" Type="String" />
                    <asp:Parameter Name="pregunta" Type="String" />
                    <asp:Parameter Name="respuesta" Type="String" />
                    <asp:Parameter Name="dni" Type="Int32" />
                    <asp:Parameter Name="confirmado" Type="Boolean" />
                    <asp:Parameter Name="grupo" Type="String" />
                    <asp:Parameter Name="tipo" Type="String" />
                    <asp:Parameter Name="email" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </asp:Panel>
    </form>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
</body>
</html>
