'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReferenceCONsvc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReferenceCONsvc.IEjemploServiceIker")>  _
    Public Interface IEjemploServiceIker
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEjemploServiceIker/GetUsuarios", ReplyAction:="http://tempuri.org/IEjemploServiceIker/GetUsuariosResponse")>  _
        Function GetUsuarios() As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEjemploServiceIkerChannel
        Inherits ServiceReferenceCONsvc.IEjemploServiceIker, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EjemploServiceIkerClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceCONsvc.IEjemploServiceIker)
        Implements ServiceReferenceCONsvc.IEjemploServiceIker
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetUsuarios() As System.Data.DataSet Implements ServiceReferenceCONsvc.IEjemploServiceIker.GetUsuarios
            Return MyBase.Channel.GetUsuarios
        End Function
    End Class
End Namespace
